- name: Cleaning up the system
  ansible.builtin.command: "{{ item }}"
  become: true
  loop:
    - rm -rf /var/log/*
    - rm -rf /var/lib/apt/lists/*
    - rm -rf /var/cache/apt/archives/*
- name: Configuring user shell
  ansible.builtin.command: "chsh -s /usr/bin/zsh agmalpartida"
  become: true

# - name: Finalizing the installation
#   ansible.builtin.command: "{{ item }}"
#   args:
#     chdir: "/home/agmalpartida"
#   loop:
#     - rm .profile .bashrc .bash_logout
#     - mkdir .config
#     - stow -d dotfiles -t "${HOME}" .
#     - /opt/pkg/nvim-linux64/bin/nvim -c "qa" >/dev/null 2>&1
