- name: Personal Development Environment
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  connection: local
  pre_tasks:
    - include_vars: '{{ item }}'
      with_fileglob:
        - '{{ playbook_dir }}/group_vars/default.yml'
  roles:
    - apt
    - github
    - pip
    - cmd
    - agmalpartida.dotfiles
  tasks:
    - include_tasks: tasks/locales.yml
    - include_tasks: tasks/kyrat.yml
