- name: Personal Development Environment
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  connection: local
  pre_tasks:
    - include_vars: '{{ item }}'
      with_fileglob:
        - '{{ playbook_dir }}/group_vars/default.yml'
    - name: ECS dir should be created
      become: no
      file:
        path: '{{ user_home }}/.ecs'
        state: directory
    - name: Kubeconfig files dir should be created
      become: no
      file:
        path: '{{ user_home }}/.kube'
        state: directory
    - name: Personal logs dir should be created
      file:
        path: '{{ user_home }}/.logs'
        owner: '{{ user }}'
        state: directory
  roles:
    - apt
    - github
    - pip
    - cmd
    #- agmalpartida.dotfiles
  tasks:
    - include_tasks: tasks/locales.yml
    - include_tasks: tasks/kyrat.yml
